### ISSUE TITLE
Possible error in Wikipedia's ITP article

### ISSUE THREAD

**Issue by waruyama** [paulnorthrop/itp#2]
I just learned about ITP yesterday and tried an implementation that is based on [Wikipedia's pseudocode implementation](https://en.wikipedia.org/wiki/ITP_method#The_algorithm) of the algorithm.

It says:
```
if yitp > 0 then b = xitp and yb = yitp
else if yitp < 0 then a = xitp and ya = yitp
else a = xitp and y = xitp
```

In [your implementation](https://github.com/paulnorthrop/itp/blob/main/src/itp_c.cpp#L161) you multiply `yITP` with the sign of `yb` in the conditions:

```
    if (yITP * signyb > 0.0) {
      new_b = xITP ;
      yb = yITP ;
    } else if (yITP * signyb < 0.0) {
      new_a = xITP ;
      ya = yITP ;
    } else {
```

I do not understand the algorithm, but changing the conditions to multiply `yitp` with the sign of `yb` (or simply `yb`) made the implementation work. Also, I know from other algorithms (like Regula Falsi) that this multiplication is done in the conditions.

Since you seem to have deep understanding of the ITP method, my question would be if you can confirm that there is an error in the algorithm in the Wikipedia article.

**Comment by paulnorthrop** [comment]
The pseudocode in the Wikipedia article "... assumes the initial values of ya and yb ... satisfy ya < 0 < yb ...", which is consistent with the plots to the right of this text. This assumption simplifies the code for updating the bracketing interval. More generally, we need to be able to handle cases where ya > 0 > yb, which is what the multiplication by the sign does.

**Comment by waruyama** [comment]
Thank you. My ya and yb did not satisfy this condition, that's why the implementation failed. So we can leave the Wikipedia article as it is and only do the multiplication in the code.
